name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
    - name: Install dependencies
      run: |
        install.packages(c("testthat", "plumber", "metafor", "assertthat", "readxl", "jsonlite", "ggplot2", "dplyr", "httr"))
      shell: Rscript {0}
    - name: Run tests
      run: |
        testthat::test_dir("tests")
      shell: Rscript {0}

  build:
    needs: test
    runs-on: ubuntu-latest
    env:
      APP_PORT: 8000
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t meta-analysis-api .
    - name: Test Docker image
      run: |
        docker run -d -p ${{ env.APP_PORT }}:${{ env.APP_PORT }} --name test-container meta-analysis-api
        sleep 5
        curl -f http://localhost:${{ env.APP_PORT }}/test || exit 1
        docker stop test-container
