name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
    - name: Install dependencies
      run: |
        install.packages(c('plumber', 'metafor', 'assertthat', 'readxl', 'jsonlite', 'ggplot2', 'dplyr', 'httr', 'testthat', 'checkmate'))
      shell: Rscript {0}
    - name: Run tests
      run: |
        Rscript tests/run_tests.R

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    env:
      APP_PORT: 8000
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: mmrech/meta-analysis-api:latest
    - name: Test Docker image
      run: |
        docker run -d -p ${{ env.APP_PORT }}:${{ env.APP_PORT }} --name test-container mmrech/meta-analysis-api:latest
        sleep 10
        curl -f http://localhost:${{ env.APP_PORT }}/health || exit 1
        docker stop test-container
        docker rm test-container
